// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/FantasyRL/go-mcp-demo/pkg/gorm-gen/model"
)

func newConversations(db *gorm.DB, opts ...gen.DOOption) conversations {
	_conversations := conversations{}

	_conversations.conversationsDo.UseDB(db, opts...)
	_conversations.conversationsDo.UseModel(&model.Conversations{})

	tableName := _conversations.conversationsDo.TableName()
	_conversations.ALL = field.NewAsterisk(tableName)
	_conversations.ID = field.NewString(tableName, "id")
	_conversations.UserID = field.NewString(tableName, "user_id")
	_conversations.Messages = field.NewString(tableName, "messages")
	_conversations.IsSummarized = field.NewInt16(tableName, "is_summarized")
	_conversations.Title = field.NewString(tableName, "title")
	_conversations.CreatedAt = field.NewTime(tableName, "created_at")
	_conversations.UpdatedAt = field.NewTime(tableName, "updated_at")
	_conversations.DeletedAt = field.NewField(tableName, "deleted_at")

	_conversations.fillFieldMap()

	return _conversations
}

type conversations struct {
	conversationsDo conversationsDo

	ALL          field.Asterisk
	ID           field.String // 对话ID
	UserID       field.String // 用户ID
	Messages     field.String // 对话消息，JSON格式存储
	IsSummarized field.Int16  // 是否已生成摘要，0-否，1-是
	Title        field.String // 对话标题
	CreatedAt    field.Time   // 创建时间
	UpdatedAt    field.Time   // 更新时间
	DeletedAt    field.Field  // 删除时间

	fieldMap map[string]field.Expr
}

func (c conversations) Table(newTableName string) *conversations {
	c.conversationsDo.UseTable(newTableName)
	return c.updateTableName(newTableName)
}

func (c conversations) As(alias string) *conversations {
	c.conversationsDo.DO = *(c.conversationsDo.As(alias).(*gen.DO))
	return c.updateTableName(alias)
}

func (c *conversations) updateTableName(table string) *conversations {
	c.ALL = field.NewAsterisk(table)
	c.ID = field.NewString(table, "id")
	c.UserID = field.NewString(table, "user_id")
	c.Messages = field.NewString(table, "messages")
	c.IsSummarized = field.NewInt16(table, "is_summarized")
	c.Title = field.NewString(table, "title")
	c.CreatedAt = field.NewTime(table, "created_at")
	c.UpdatedAt = field.NewTime(table, "updated_at")
	c.DeletedAt = field.NewField(table, "deleted_at")

	c.fillFieldMap()

	return c
}

func (c *conversations) WithContext(ctx context.Context) IConversationsDo {
	return c.conversationsDo.WithContext(ctx)
}

func (c conversations) TableName() string { return c.conversationsDo.TableName() }

func (c conversations) Alias() string { return c.conversationsDo.Alias() }

func (c conversations) Columns(cols ...field.Expr) gen.Columns {
	return c.conversationsDo.Columns(cols...)
}

func (c *conversations) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := c.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (c *conversations) fillFieldMap() {
	c.fieldMap = make(map[string]field.Expr, 8)
	c.fieldMap["id"] = c.ID
	c.fieldMap["user_id"] = c.UserID
	c.fieldMap["messages"] = c.Messages
	c.fieldMap["is_summarized"] = c.IsSummarized
	c.fieldMap["title"] = c.Title
	c.fieldMap["created_at"] = c.CreatedAt
	c.fieldMap["updated_at"] = c.UpdatedAt
	c.fieldMap["deleted_at"] = c.DeletedAt
}

func (c conversations) clone(db *gorm.DB) conversations {
	c.conversationsDo.ReplaceConnPool(db.Statement.ConnPool)
	return c
}

func (c conversations) replaceDB(db *gorm.DB) conversations {
	c.conversationsDo.ReplaceDB(db)
	return c
}

type conversationsDo struct{ gen.DO }

type IConversationsDo interface {
	gen.SubQuery
	Debug() IConversationsDo
	WithContext(ctx context.Context) IConversationsDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IConversationsDo
	WriteDB() IConversationsDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IConversationsDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IConversationsDo
	Not(conds ...gen.Condition) IConversationsDo
	Or(conds ...gen.Condition) IConversationsDo
	Select(conds ...field.Expr) IConversationsDo
	Where(conds ...gen.Condition) IConversationsDo
	Order(conds ...field.Expr) IConversationsDo
	Distinct(cols ...field.Expr) IConversationsDo
	Omit(cols ...field.Expr) IConversationsDo
	Join(table schema.Tabler, on ...field.Expr) IConversationsDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IConversationsDo
	RightJoin(table schema.Tabler, on ...field.Expr) IConversationsDo
	Group(cols ...field.Expr) IConversationsDo
	Having(conds ...gen.Condition) IConversationsDo
	Limit(limit int) IConversationsDo
	Offset(offset int) IConversationsDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IConversationsDo
	Unscoped() IConversationsDo
	Create(values ...*model.Conversations) error
	CreateInBatches(values []*model.Conversations, batchSize int) error
	Save(values ...*model.Conversations) error
	First() (*model.Conversations, error)
	Take() (*model.Conversations, error)
	Last() (*model.Conversations, error)
	Find() ([]*model.Conversations, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.Conversations, err error)
	FindInBatches(result *[]*model.Conversations, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.Conversations) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IConversationsDo
	Assign(attrs ...field.AssignExpr) IConversationsDo
	Joins(fields ...field.RelationField) IConversationsDo
	Preload(fields ...field.RelationField) IConversationsDo
	FirstOrInit() (*model.Conversations, error)
	FirstOrCreate() (*model.Conversations, error)
	FindByPage(offset int, limit int) (result []*model.Conversations, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IConversationsDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (c conversationsDo) Debug() IConversationsDo {
	return c.withDO(c.DO.Debug())
}

func (c conversationsDo) WithContext(ctx context.Context) IConversationsDo {
	return c.withDO(c.DO.WithContext(ctx))
}

func (c conversationsDo) ReadDB() IConversationsDo {
	return c.Clauses(dbresolver.Read)
}

func (c conversationsDo) WriteDB() IConversationsDo {
	return c.Clauses(dbresolver.Write)
}

func (c conversationsDo) Session(config *gorm.Session) IConversationsDo {
	return c.withDO(c.DO.Session(config))
}

func (c conversationsDo) Clauses(conds ...clause.Expression) IConversationsDo {
	return c.withDO(c.DO.Clauses(conds...))
}

func (c conversationsDo) Returning(value interface{}, columns ...string) IConversationsDo {
	return c.withDO(c.DO.Returning(value, columns...))
}

func (c conversationsDo) Not(conds ...gen.Condition) IConversationsDo {
	return c.withDO(c.DO.Not(conds...))
}

func (c conversationsDo) Or(conds ...gen.Condition) IConversationsDo {
	return c.withDO(c.DO.Or(conds...))
}

func (c conversationsDo) Select(conds ...field.Expr) IConversationsDo {
	return c.withDO(c.DO.Select(conds...))
}

func (c conversationsDo) Where(conds ...gen.Condition) IConversationsDo {
	return c.withDO(c.DO.Where(conds...))
}

func (c conversationsDo) Order(conds ...field.Expr) IConversationsDo {
	return c.withDO(c.DO.Order(conds...))
}

func (c conversationsDo) Distinct(cols ...field.Expr) IConversationsDo {
	return c.withDO(c.DO.Distinct(cols...))
}

func (c conversationsDo) Omit(cols ...field.Expr) IConversationsDo {
	return c.withDO(c.DO.Omit(cols...))
}

func (c conversationsDo) Join(table schema.Tabler, on ...field.Expr) IConversationsDo {
	return c.withDO(c.DO.Join(table, on...))
}

func (c conversationsDo) LeftJoin(table schema.Tabler, on ...field.Expr) IConversationsDo {
	return c.withDO(c.DO.LeftJoin(table, on...))
}

func (c conversationsDo) RightJoin(table schema.Tabler, on ...field.Expr) IConversationsDo {
	return c.withDO(c.DO.RightJoin(table, on...))
}

func (c conversationsDo) Group(cols ...field.Expr) IConversationsDo {
	return c.withDO(c.DO.Group(cols...))
}

func (c conversationsDo) Having(conds ...gen.Condition) IConversationsDo {
	return c.withDO(c.DO.Having(conds...))
}

func (c conversationsDo) Limit(limit int) IConversationsDo {
	return c.withDO(c.DO.Limit(limit))
}

func (c conversationsDo) Offset(offset int) IConversationsDo {
	return c.withDO(c.DO.Offset(offset))
}

func (c conversationsDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IConversationsDo {
	return c.withDO(c.DO.Scopes(funcs...))
}

func (c conversationsDo) Unscoped() IConversationsDo {
	return c.withDO(c.DO.Unscoped())
}

func (c conversationsDo) Create(values ...*model.Conversations) error {
	if len(values) == 0 {
		return nil
	}
	return c.DO.Create(values)
}

func (c conversationsDo) CreateInBatches(values []*model.Conversations, batchSize int) error {
	return c.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (c conversationsDo) Save(values ...*model.Conversations) error {
	if len(values) == 0 {
		return nil
	}
	return c.DO.Save(values)
}

func (c conversationsDo) First() (*model.Conversations, error) {
	if result, err := c.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.Conversations), nil
	}
}

func (c conversationsDo) Take() (*model.Conversations, error) {
	if result, err := c.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.Conversations), nil
	}
}

func (c conversationsDo) Last() (*model.Conversations, error) {
	if result, err := c.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.Conversations), nil
	}
}

func (c conversationsDo) Find() ([]*model.Conversations, error) {
	result, err := c.DO.Find()
	return result.([]*model.Conversations), err
}

func (c conversationsDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.Conversations, err error) {
	buf := make([]*model.Conversations, 0, batchSize)
	err = c.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (c conversationsDo) FindInBatches(result *[]*model.Conversations, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return c.DO.FindInBatches(result, batchSize, fc)
}

func (c conversationsDo) Attrs(attrs ...field.AssignExpr) IConversationsDo {
	return c.withDO(c.DO.Attrs(attrs...))
}

func (c conversationsDo) Assign(attrs ...field.AssignExpr) IConversationsDo {
	return c.withDO(c.DO.Assign(attrs...))
}

func (c conversationsDo) Joins(fields ...field.RelationField) IConversationsDo {
	for _, _f := range fields {
		c = *c.withDO(c.DO.Joins(_f))
	}
	return &c
}

func (c conversationsDo) Preload(fields ...field.RelationField) IConversationsDo {
	for _, _f := range fields {
		c = *c.withDO(c.DO.Preload(_f))
	}
	return &c
}

func (c conversationsDo) FirstOrInit() (*model.Conversations, error) {
	if result, err := c.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.Conversations), nil
	}
}

func (c conversationsDo) FirstOrCreate() (*model.Conversations, error) {
	if result, err := c.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.Conversations), nil
	}
}

func (c conversationsDo) FindByPage(offset int, limit int) (result []*model.Conversations, count int64, err error) {
	result, err = c.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = c.Offset(-1).Limit(-1).Count()
	return
}

func (c conversationsDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = c.Count()
	if err != nil {
		return
	}

	err = c.Offset(offset).Limit(limit).Scan(result)
	return
}

func (c conversationsDo) Scan(result interface{}) (err error) {
	return c.DO.Scan(result)
}

func (c conversationsDo) Delete(models ...*model.Conversations) (result gen.ResultInfo, err error) {
	return c.DO.Delete(models)
}

func (c *conversationsDo) withDO(do gen.Dao) *conversationsDo {
	c.DO = *do.(*gen.DO)
	return c
}
