// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/FantasyRL/go-mcp-demo/pkg/gorm-gen/model"
)

func newSummaries(db *gorm.DB, opts ...gen.DOOption) summaries {
	_summaries := summaries{}

	_summaries.summariesDo.UseDB(db, opts...)
	_summaries.summariesDo.UseModel(&model.Summaries{})

	tableName := _summaries.summariesDo.TableName()
	_summaries.ALL = field.NewAsterisk(tableName)
	_summaries.ID = field.NewString(tableName, "id")
	_summaries.ConversationID = field.NewString(tableName, "conversation_id")
	_summaries.SummaryText = field.NewString(tableName, "summary_text")
	_summaries.CreatedAt = field.NewTime(tableName, "created_at")
	_summaries.UpdatedAt = field.NewTime(tableName, "updated_at")
	_summaries.DeletedAt = field.NewField(tableName, "deleted_at")

	_summaries.fillFieldMap()

	return _summaries
}

type summaries struct {
	summariesDo summariesDo

	ALL            field.Asterisk
	ID             field.String // 摘要ID
	ConversationID field.String // 对话ID
	SummaryText    field.String // 摘要内容
	CreatedAt      field.Time   // 创建时间
	UpdatedAt      field.Time   // 更新时间
	DeletedAt      field.Field  // 删除时间

	fieldMap map[string]field.Expr
}

func (s summaries) Table(newTableName string) *summaries {
	s.summariesDo.UseTable(newTableName)
	return s.updateTableName(newTableName)
}

func (s summaries) As(alias string) *summaries {
	s.summariesDo.DO = *(s.summariesDo.As(alias).(*gen.DO))
	return s.updateTableName(alias)
}

func (s *summaries) updateTableName(table string) *summaries {
	s.ALL = field.NewAsterisk(table)
	s.ID = field.NewString(table, "id")
	s.ConversationID = field.NewString(table, "conversation_id")
	s.SummaryText = field.NewString(table, "summary_text")
	s.CreatedAt = field.NewTime(table, "created_at")
	s.UpdatedAt = field.NewTime(table, "updated_at")
	s.DeletedAt = field.NewField(table, "deleted_at")

	s.fillFieldMap()

	return s
}

func (s *summaries) WithContext(ctx context.Context) ISummariesDo {
	return s.summariesDo.WithContext(ctx)
}

func (s summaries) TableName() string { return s.summariesDo.TableName() }

func (s summaries) Alias() string { return s.summariesDo.Alias() }

func (s summaries) Columns(cols ...field.Expr) gen.Columns { return s.summariesDo.Columns(cols...) }

func (s *summaries) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := s.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (s *summaries) fillFieldMap() {
	s.fieldMap = make(map[string]field.Expr, 6)
	s.fieldMap["id"] = s.ID
	s.fieldMap["conversation_id"] = s.ConversationID
	s.fieldMap["summary_text"] = s.SummaryText
	s.fieldMap["created_at"] = s.CreatedAt
	s.fieldMap["updated_at"] = s.UpdatedAt
	s.fieldMap["deleted_at"] = s.DeletedAt
}

func (s summaries) clone(db *gorm.DB) summaries {
	s.summariesDo.ReplaceConnPool(db.Statement.ConnPool)
	return s
}

func (s summaries) replaceDB(db *gorm.DB) summaries {
	s.summariesDo.ReplaceDB(db)
	return s
}

type summariesDo struct{ gen.DO }

type ISummariesDo interface {
	gen.SubQuery
	Debug() ISummariesDo
	WithContext(ctx context.Context) ISummariesDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() ISummariesDo
	WriteDB() ISummariesDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) ISummariesDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) ISummariesDo
	Not(conds ...gen.Condition) ISummariesDo
	Or(conds ...gen.Condition) ISummariesDo
	Select(conds ...field.Expr) ISummariesDo
	Where(conds ...gen.Condition) ISummariesDo
	Order(conds ...field.Expr) ISummariesDo
	Distinct(cols ...field.Expr) ISummariesDo
	Omit(cols ...field.Expr) ISummariesDo
	Join(table schema.Tabler, on ...field.Expr) ISummariesDo
	LeftJoin(table schema.Tabler, on ...field.Expr) ISummariesDo
	RightJoin(table schema.Tabler, on ...field.Expr) ISummariesDo
	Group(cols ...field.Expr) ISummariesDo
	Having(conds ...gen.Condition) ISummariesDo
	Limit(limit int) ISummariesDo
	Offset(offset int) ISummariesDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) ISummariesDo
	Unscoped() ISummariesDo
	Create(values ...*model.Summaries) error
	CreateInBatches(values []*model.Summaries, batchSize int) error
	Save(values ...*model.Summaries) error
	First() (*model.Summaries, error)
	Take() (*model.Summaries, error)
	Last() (*model.Summaries, error)
	Find() ([]*model.Summaries, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.Summaries, err error)
	FindInBatches(result *[]*model.Summaries, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.Summaries) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) ISummariesDo
	Assign(attrs ...field.AssignExpr) ISummariesDo
	Joins(fields ...field.RelationField) ISummariesDo
	Preload(fields ...field.RelationField) ISummariesDo
	FirstOrInit() (*model.Summaries, error)
	FirstOrCreate() (*model.Summaries, error)
	FindByPage(offset int, limit int) (result []*model.Summaries, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) ISummariesDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (s summariesDo) Debug() ISummariesDo {
	return s.withDO(s.DO.Debug())
}

func (s summariesDo) WithContext(ctx context.Context) ISummariesDo {
	return s.withDO(s.DO.WithContext(ctx))
}

func (s summariesDo) ReadDB() ISummariesDo {
	return s.Clauses(dbresolver.Read)
}

func (s summariesDo) WriteDB() ISummariesDo {
	return s.Clauses(dbresolver.Write)
}

func (s summariesDo) Session(config *gorm.Session) ISummariesDo {
	return s.withDO(s.DO.Session(config))
}

func (s summariesDo) Clauses(conds ...clause.Expression) ISummariesDo {
	return s.withDO(s.DO.Clauses(conds...))
}

func (s summariesDo) Returning(value interface{}, columns ...string) ISummariesDo {
	return s.withDO(s.DO.Returning(value, columns...))
}

func (s summariesDo) Not(conds ...gen.Condition) ISummariesDo {
	return s.withDO(s.DO.Not(conds...))
}

func (s summariesDo) Or(conds ...gen.Condition) ISummariesDo {
	return s.withDO(s.DO.Or(conds...))
}

func (s summariesDo) Select(conds ...field.Expr) ISummariesDo {
	return s.withDO(s.DO.Select(conds...))
}

func (s summariesDo) Where(conds ...gen.Condition) ISummariesDo {
	return s.withDO(s.DO.Where(conds...))
}

func (s summariesDo) Order(conds ...field.Expr) ISummariesDo {
	return s.withDO(s.DO.Order(conds...))
}

func (s summariesDo) Distinct(cols ...field.Expr) ISummariesDo {
	return s.withDO(s.DO.Distinct(cols...))
}

func (s summariesDo) Omit(cols ...field.Expr) ISummariesDo {
	return s.withDO(s.DO.Omit(cols...))
}

func (s summariesDo) Join(table schema.Tabler, on ...field.Expr) ISummariesDo {
	return s.withDO(s.DO.Join(table, on...))
}

func (s summariesDo) LeftJoin(table schema.Tabler, on ...field.Expr) ISummariesDo {
	return s.withDO(s.DO.LeftJoin(table, on...))
}

func (s summariesDo) RightJoin(table schema.Tabler, on ...field.Expr) ISummariesDo {
	return s.withDO(s.DO.RightJoin(table, on...))
}

func (s summariesDo) Group(cols ...field.Expr) ISummariesDo {
	return s.withDO(s.DO.Group(cols...))
}

func (s summariesDo) Having(conds ...gen.Condition) ISummariesDo {
	return s.withDO(s.DO.Having(conds...))
}

func (s summariesDo) Limit(limit int) ISummariesDo {
	return s.withDO(s.DO.Limit(limit))
}

func (s summariesDo) Offset(offset int) ISummariesDo {
	return s.withDO(s.DO.Offset(offset))
}

func (s summariesDo) Scopes(funcs ...func(gen.Dao) gen.Dao) ISummariesDo {
	return s.withDO(s.DO.Scopes(funcs...))
}

func (s summariesDo) Unscoped() ISummariesDo {
	return s.withDO(s.DO.Unscoped())
}

func (s summariesDo) Create(values ...*model.Summaries) error {
	if len(values) == 0 {
		return nil
	}
	return s.DO.Create(values)
}

func (s summariesDo) CreateInBatches(values []*model.Summaries, batchSize int) error {
	return s.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (s summariesDo) Save(values ...*model.Summaries) error {
	if len(values) == 0 {
		return nil
	}
	return s.DO.Save(values)
}

func (s summariesDo) First() (*model.Summaries, error) {
	if result, err := s.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.Summaries), nil
	}
}

func (s summariesDo) Take() (*model.Summaries, error) {
	if result, err := s.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.Summaries), nil
	}
}

func (s summariesDo) Last() (*model.Summaries, error) {
	if result, err := s.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.Summaries), nil
	}
}

func (s summariesDo) Find() ([]*model.Summaries, error) {
	result, err := s.DO.Find()
	return result.([]*model.Summaries), err
}

func (s summariesDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.Summaries, err error) {
	buf := make([]*model.Summaries, 0, batchSize)
	err = s.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (s summariesDo) FindInBatches(result *[]*model.Summaries, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return s.DO.FindInBatches(result, batchSize, fc)
}

func (s summariesDo) Attrs(attrs ...field.AssignExpr) ISummariesDo {
	return s.withDO(s.DO.Attrs(attrs...))
}

func (s summariesDo) Assign(attrs ...field.AssignExpr) ISummariesDo {
	return s.withDO(s.DO.Assign(attrs...))
}

func (s summariesDo) Joins(fields ...field.RelationField) ISummariesDo {
	for _, _f := range fields {
		s = *s.withDO(s.DO.Joins(_f))
	}
	return &s
}

func (s summariesDo) Preload(fields ...field.RelationField) ISummariesDo {
	for _, _f := range fields {
		s = *s.withDO(s.DO.Preload(_f))
	}
	return &s
}

func (s summariesDo) FirstOrInit() (*model.Summaries, error) {
	if result, err := s.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.Summaries), nil
	}
}

func (s summariesDo) FirstOrCreate() (*model.Summaries, error) {
	if result, err := s.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.Summaries), nil
	}
}

func (s summariesDo) FindByPage(offset int, limit int) (result []*model.Summaries, count int64, err error) {
	result, err = s.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = s.Offset(-1).Limit(-1).Count()
	return
}

func (s summariesDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = s.Count()
	if err != nil {
		return
	}

	err = s.Offset(offset).Limit(limit).Scan(result)
	return
}

func (s summariesDo) Scan(result interface{}) (err error) {
	return s.DO.Scan(result)
}

func (s summariesDo) Delete(models ...*model.Summaries) (result gen.ResultInfo, err error) {
	return s.DO.Delete(models)
}

func (s *summariesDo) withDO(do gen.Dao) *summariesDo {
	s.DO = *do.(*gen.DO)
	return s
}
