// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/FantasyRL/go-mcp-demo/pkg/gorm-gen/model"
)

func newTodolists(db *gorm.DB, opts ...gen.DOOption) todolists {
	_todolists := todolists{}

	_todolists.todolistsDo.UseDB(db, opts...)
	_todolists.todolistsDo.UseModel(&model.Todolists{})

	tableName := _todolists.todolistsDo.TableName()
	_todolists.ALL = field.NewAsterisk(tableName)
	_todolists.ID = field.NewString(tableName, "id")
	_todolists.UserID = field.NewString(tableName, "user_id")
	_todolists.Title = field.NewString(tableName, "title")
	_todolists.Content = field.NewString(tableName, "content")
	_todolists.StartTime = field.NewTime(tableName, "start_time")
	_todolists.EndTime = field.NewTime(tableName, "end_time")
	_todolists.IsAllDay = field.NewInt16(tableName, "is_all_day")
	_todolists.Status = field.NewInt16(tableName, "status")
	_todolists.RemindAt = field.NewTime(tableName, "remind_at")
	_todolists.Tag = field.NewString(tableName, "tag")
	_todolists.CreatedAt = field.NewTime(tableName, "created_at")
	_todolists.UpdatedAt = field.NewTime(tableName, "updated_at")
	_todolists.DeletedAt = field.NewField(tableName, "deleted_at")

	_todolists.fillFieldMap()

	return _todolists
}

type todolists struct {
	todolistsDo todolistsDo

	ALL       field.Asterisk
	ID        field.String // 待办事项ID
	UserID    field.String // 用户ID
	Title     field.String // 待办事项标题
	Content   field.String // 待办事项内容
	StartTime field.Time   // 待办事项开始时间
	EndTime   field.Time   // 待办事项结束时间
	IsAllDay  field.Int16  // 是否为全天事项，0-否，1-是
	Status    field.Int16  // 待办事项状态，0-未完成，1-已完成
	RemindAt  field.Time   // 待办事项提醒时间
	Tag       field.String // 待办事项标签
	CreatedAt field.Time   // 创建时间
	UpdatedAt field.Time   // 更新时间
	DeletedAt field.Field  // 删除时间

	fieldMap map[string]field.Expr
}

func (t todolists) Table(newTableName string) *todolists {
	t.todolistsDo.UseTable(newTableName)
	return t.updateTableName(newTableName)
}

func (t todolists) As(alias string) *todolists {
	t.todolistsDo.DO = *(t.todolistsDo.As(alias).(*gen.DO))
	return t.updateTableName(alias)
}

func (t *todolists) updateTableName(table string) *todolists {
	t.ALL = field.NewAsterisk(table)
	t.ID = field.NewString(table, "id")
	t.UserID = field.NewString(table, "user_id")
	t.Title = field.NewString(table, "title")
	t.Content = field.NewString(table, "content")
	t.StartTime = field.NewTime(table, "start_time")
	t.EndTime = field.NewTime(table, "end_time")
	t.IsAllDay = field.NewInt16(table, "is_all_day")
	t.Status = field.NewInt16(table, "status")
	t.RemindAt = field.NewTime(table, "remind_at")
	t.Tag = field.NewString(table, "tag")
	t.CreatedAt = field.NewTime(table, "created_at")
	t.UpdatedAt = field.NewTime(table, "updated_at")
	t.DeletedAt = field.NewField(table, "deleted_at")

	t.fillFieldMap()

	return t
}

func (t *todolists) WithContext(ctx context.Context) ITodolistsDo {
	return t.todolistsDo.WithContext(ctx)
}

func (t todolists) TableName() string { return t.todolistsDo.TableName() }

func (t todolists) Alias() string { return t.todolistsDo.Alias() }

func (t todolists) Columns(cols ...field.Expr) gen.Columns { return t.todolistsDo.Columns(cols...) }

func (t *todolists) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := t.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (t *todolists) fillFieldMap() {
	t.fieldMap = make(map[string]field.Expr, 13)
	t.fieldMap["id"] = t.ID
	t.fieldMap["user_id"] = t.UserID
	t.fieldMap["title"] = t.Title
	t.fieldMap["content"] = t.Content
	t.fieldMap["start_time"] = t.StartTime
	t.fieldMap["end_time"] = t.EndTime
	t.fieldMap["is_all_day"] = t.IsAllDay
	t.fieldMap["status"] = t.Status
	t.fieldMap["remind_at"] = t.RemindAt
	t.fieldMap["tag"] = t.Tag
	t.fieldMap["created_at"] = t.CreatedAt
	t.fieldMap["updated_at"] = t.UpdatedAt
	t.fieldMap["deleted_at"] = t.DeletedAt
}

func (t todolists) clone(db *gorm.DB) todolists {
	t.todolistsDo.ReplaceConnPool(db.Statement.ConnPool)
	return t
}

func (t todolists) replaceDB(db *gorm.DB) todolists {
	t.todolistsDo.ReplaceDB(db)
	return t
}

type todolistsDo struct{ gen.DO }

type ITodolistsDo interface {
	gen.SubQuery
	Debug() ITodolistsDo
	WithContext(ctx context.Context) ITodolistsDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() ITodolistsDo
	WriteDB() ITodolistsDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) ITodolistsDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) ITodolistsDo
	Not(conds ...gen.Condition) ITodolistsDo
	Or(conds ...gen.Condition) ITodolistsDo
	Select(conds ...field.Expr) ITodolistsDo
	Where(conds ...gen.Condition) ITodolistsDo
	Order(conds ...field.Expr) ITodolistsDo
	Distinct(cols ...field.Expr) ITodolistsDo
	Omit(cols ...field.Expr) ITodolistsDo
	Join(table schema.Tabler, on ...field.Expr) ITodolistsDo
	LeftJoin(table schema.Tabler, on ...field.Expr) ITodolistsDo
	RightJoin(table schema.Tabler, on ...field.Expr) ITodolistsDo
	Group(cols ...field.Expr) ITodolistsDo
	Having(conds ...gen.Condition) ITodolistsDo
	Limit(limit int) ITodolistsDo
	Offset(offset int) ITodolistsDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) ITodolistsDo
	Unscoped() ITodolistsDo
	Create(values ...*model.Todolists) error
	CreateInBatches(values []*model.Todolists, batchSize int) error
	Save(values ...*model.Todolists) error
	First() (*model.Todolists, error)
	Take() (*model.Todolists, error)
	Last() (*model.Todolists, error)
	Find() ([]*model.Todolists, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.Todolists, err error)
	FindInBatches(result *[]*model.Todolists, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.Todolists) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) ITodolistsDo
	Assign(attrs ...field.AssignExpr) ITodolistsDo
	Joins(fields ...field.RelationField) ITodolistsDo
	Preload(fields ...field.RelationField) ITodolistsDo
	FirstOrInit() (*model.Todolists, error)
	FirstOrCreate() (*model.Todolists, error)
	FindByPage(offset int, limit int) (result []*model.Todolists, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) ITodolistsDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (t todolistsDo) Debug() ITodolistsDo {
	return t.withDO(t.DO.Debug())
}

func (t todolistsDo) WithContext(ctx context.Context) ITodolistsDo {
	return t.withDO(t.DO.WithContext(ctx))
}

func (t todolistsDo) ReadDB() ITodolistsDo {
	return t.Clauses(dbresolver.Read)
}

func (t todolistsDo) WriteDB() ITodolistsDo {
	return t.Clauses(dbresolver.Write)
}

func (t todolistsDo) Session(config *gorm.Session) ITodolistsDo {
	return t.withDO(t.DO.Session(config))
}

func (t todolistsDo) Clauses(conds ...clause.Expression) ITodolistsDo {
	return t.withDO(t.DO.Clauses(conds...))
}

func (t todolistsDo) Returning(value interface{}, columns ...string) ITodolistsDo {
	return t.withDO(t.DO.Returning(value, columns...))
}

func (t todolistsDo) Not(conds ...gen.Condition) ITodolistsDo {
	return t.withDO(t.DO.Not(conds...))
}

func (t todolistsDo) Or(conds ...gen.Condition) ITodolistsDo {
	return t.withDO(t.DO.Or(conds...))
}

func (t todolistsDo) Select(conds ...field.Expr) ITodolistsDo {
	return t.withDO(t.DO.Select(conds...))
}

func (t todolistsDo) Where(conds ...gen.Condition) ITodolistsDo {
	return t.withDO(t.DO.Where(conds...))
}

func (t todolistsDo) Order(conds ...field.Expr) ITodolistsDo {
	return t.withDO(t.DO.Order(conds...))
}

func (t todolistsDo) Distinct(cols ...field.Expr) ITodolistsDo {
	return t.withDO(t.DO.Distinct(cols...))
}

func (t todolistsDo) Omit(cols ...field.Expr) ITodolistsDo {
	return t.withDO(t.DO.Omit(cols...))
}

func (t todolistsDo) Join(table schema.Tabler, on ...field.Expr) ITodolistsDo {
	return t.withDO(t.DO.Join(table, on...))
}

func (t todolistsDo) LeftJoin(table schema.Tabler, on ...field.Expr) ITodolistsDo {
	return t.withDO(t.DO.LeftJoin(table, on...))
}

func (t todolistsDo) RightJoin(table schema.Tabler, on ...field.Expr) ITodolistsDo {
	return t.withDO(t.DO.RightJoin(table, on...))
}

func (t todolistsDo) Group(cols ...field.Expr) ITodolistsDo {
	return t.withDO(t.DO.Group(cols...))
}

func (t todolistsDo) Having(conds ...gen.Condition) ITodolistsDo {
	return t.withDO(t.DO.Having(conds...))
}

func (t todolistsDo) Limit(limit int) ITodolistsDo {
	return t.withDO(t.DO.Limit(limit))
}

func (t todolistsDo) Offset(offset int) ITodolistsDo {
	return t.withDO(t.DO.Offset(offset))
}

func (t todolistsDo) Scopes(funcs ...func(gen.Dao) gen.Dao) ITodolistsDo {
	return t.withDO(t.DO.Scopes(funcs...))
}

func (t todolistsDo) Unscoped() ITodolistsDo {
	return t.withDO(t.DO.Unscoped())
}

func (t todolistsDo) Create(values ...*model.Todolists) error {
	if len(values) == 0 {
		return nil
	}
	return t.DO.Create(values)
}

func (t todolistsDo) CreateInBatches(values []*model.Todolists, batchSize int) error {
	return t.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (t todolistsDo) Save(values ...*model.Todolists) error {
	if len(values) == 0 {
		return nil
	}
	return t.DO.Save(values)
}

func (t todolistsDo) First() (*model.Todolists, error) {
	if result, err := t.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.Todolists), nil
	}
}

func (t todolistsDo) Take() (*model.Todolists, error) {
	if result, err := t.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.Todolists), nil
	}
}

func (t todolistsDo) Last() (*model.Todolists, error) {
	if result, err := t.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.Todolists), nil
	}
}

func (t todolistsDo) Find() ([]*model.Todolists, error) {
	result, err := t.DO.Find()
	return result.([]*model.Todolists), err
}

func (t todolistsDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.Todolists, err error) {
	buf := make([]*model.Todolists, 0, batchSize)
	err = t.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (t todolistsDo) FindInBatches(result *[]*model.Todolists, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return t.DO.FindInBatches(result, batchSize, fc)
}

func (t todolistsDo) Attrs(attrs ...field.AssignExpr) ITodolistsDo {
	return t.withDO(t.DO.Attrs(attrs...))
}

func (t todolistsDo) Assign(attrs ...field.AssignExpr) ITodolistsDo {
	return t.withDO(t.DO.Assign(attrs...))
}

func (t todolistsDo) Joins(fields ...field.RelationField) ITodolistsDo {
	for _, _f := range fields {
		t = *t.withDO(t.DO.Joins(_f))
	}
	return &t
}

func (t todolistsDo) Preload(fields ...field.RelationField) ITodolistsDo {
	for _, _f := range fields {
		t = *t.withDO(t.DO.Preload(_f))
	}
	return &t
}

func (t todolistsDo) FirstOrInit() (*model.Todolists, error) {
	if result, err := t.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.Todolists), nil
	}
}

func (t todolistsDo) FirstOrCreate() (*model.Todolists, error) {
	if result, err := t.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.Todolists), nil
	}
}

func (t todolistsDo) FindByPage(offset int, limit int) (result []*model.Todolists, count int64, err error) {
	result, err = t.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = t.Offset(-1).Limit(-1).Count()
	return
}

func (t todolistsDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = t.Count()
	if err != nil {
		return
	}

	err = t.Offset(offset).Limit(limit).Scan(result)
	return
}

func (t todolistsDo) Scan(result interface{}) (err error) {
	return t.DO.Scan(result)
}

func (t todolistsDo) Delete(models ...*model.Todolists) (result gen.ResultInfo, err error) {
	return t.DO.Delete(models)
}

func (t *todolistsDo) withDO(do gen.Dao) *todolistsDo {
	t.DO = *do.(*gen.DO)
	return t
}
