// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameConversations = "conversations"

// Conversations mapped from table <conversations>
type Conversations struct {
	ID           string         `gorm:"column:id;type:uuid;primaryKey;comment:对话ID" json:"id"`                                                                               // 对话ID
	UserID       string         `gorm:"column:user_id;type:character varying(32);not null;comment:用户ID" json:"user_id"`                                                      // 用户ID
	Messages     string         `gorm:"column:messages;type:jsonb;not null;comment:对话消息，JSON格式存储" json:"messages"`                                                           // 对话消息，JSON格式存储
	IsSummarized int16          `gorm:"column:is_summarized;type:smallint;not null;comment:是否已生成摘要，0-否，1-是" json:"is_summarized"`                                            // 是否已生成摘要，0-否，1-是
	Title        *string        `gorm:"column:title;type:character varying(128);comment:对话标题" json:"title"`                                                                  // 对话标题
	CreatedAt    time.Time      `gorm:"column:created_at;type:timestamp without time zone;not null;default:now();autoCreateTime;comment:创建时间" json:"created_at"`             // 创建时间
	UpdatedAt    time.Time      `gorm:"column:updated_at;type:timestamp(6) with time zone;not null;default:CURRENT_TIMESTAMP;autoUpdateTime;comment:更新时间" json:"updated_at"` // 更新时间
	DeletedAt    gorm.DeletedAt `gorm:"column:deleted_at;type:timestamp without time zone;comment:删除时间" json:"deleted_at"`                                                   // 删除时间
}

// TableName Conversations's table name
func (*Conversations) TableName() string {
	return TableNameConversations
}
