// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameSummaries = "summaries"

// Summaries mapped from table <summaries>
type Summaries struct {
	ID             string         `gorm:"column:id;type:uuid;primaryKey;default:gen_random_uuid();comment:摘要ID" json:"id"`                                                     // 摘要ID
	ConversationID string         `gorm:"column:conversation_id;type:uuid;not null;comment:对话ID" json:"conversation_id"`                                                       // 对话ID
	SummaryText    string         `gorm:"column:summary_text;type:text;not null;comment:摘要内容" json:"summary_text"`                                                             // 摘要内容
	CreatedAt      time.Time      `gorm:"column:created_at;type:timestamp without time zone;not null;default:now();autoCreateTime;comment:创建时间" json:"created_at"`             // 创建时间
	UpdatedAt      time.Time      `gorm:"column:updated_at;type:timestamp(6) with time zone;not null;default:CURRENT_TIMESTAMP;autoUpdateTime;comment:更新时间" json:"updated_at"` // 更新时间
	DeletedAt      gorm.DeletedAt `gorm:"column:deleted_at;type:timestamp without time zone;comment:删除时间" json:"deleted_at"`                                                   // 删除时间
}

// TableName Summaries's table name
func (*Summaries) TableName() string {
	return TableNameSummaries
}
