// Code generated by hertz generator.

package api

import (
	"github.com/FantasyRL/go-mcp-demo/api/mw"
	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _apiMw() []app.HandlerFunc {
	return []app.HandlerFunc{
		mw.GetHeader(), // 把教务处 id+cookie 注入 ctx
	}
}

func _v1Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _chatMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _chat0Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _chatsseMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _templateMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _conversationMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _summarizeconversationMw() []app.HandlerFunc {
	// your code...
	return nil
}
