// Code generated by hertz generator.

package api

import (
	"github.com/FantasyRL/go-mcp-demo/api/mw"
	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _apiMw() []app.HandlerFunc {
	return nil
}

func _v1Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _chatMw() []app.HandlerFunc {
	return []app.HandlerFunc{
		mw.Auth(),
		mw.GetHeaderParams(),
	}
}

func _chat0Mw() []app.HandlerFunc {
	return []app.HandlerFunc{
		mw.Auth(),
		mw.GetHeaderParams(),
	}
}

func _chatsseMw() []app.HandlerFunc {
	return nil
}

func _templateMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _conversationMw() []app.HandlerFunc {
	return []app.HandlerFunc{
		mw.Auth(),
		mw.GetHeaderParams(),
	}
}

func _summarizeconversationMw() []app.HandlerFunc {
	return []app.HandlerFunc{
		mw.Auth(),
		mw.GetHeaderParams(),
	}
}

func _getaccesstokenMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _userMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getuserinfoMw() []app.HandlerFunc {
	return []app.HandlerFunc{
		mw.GetHeaderParams(),
		mw.Auth(),
	}
}

func _getlogindataMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getconversationhistoryMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _deletetodoMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _todoMw() []app.HandlerFunc {
	return []app.HandlerFunc{
		mw.GetHeaderParams(),
		mw.Auth(),
	}
}

func _gettodoMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _listtodoMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _createtodoMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _updatetodoMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _courseMw() []app.HandlerFunc {
	return []app.HandlerFunc{
		mw.GetHeaderParams(),
		mw.Auth(),
	}
}

func _getcourselistMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _termMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _gettermlistMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _searchtodoMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _summaryMw() []app.HandlerFunc {
	// your code...
	return []app.HandlerFunc{
		mw.Auth(),
	}
}

func _deletesummaryMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getsummaryMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _listsummaryMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _updatesummaryMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _listconversationsMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _updateusersettingMw() []app.HandlerFunc {
	return []app.HandlerFunc{
		mw.Auth(),
		mw.GetHeaderParams(),
	}
}

func _termsMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _gettermMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _gettermslistMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _deleteconversationMw() []app.HandlerFunc {
	return []app.HandlerFunc{
		mw.GetHeaderParams(),
		mw.Auth(),
	}
}

func _scheduleMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _dailyscheduleMw() []app.HandlerFunc {
	return []app.HandlerFunc{
		mw.Auth(),
		mw.GetHeaderParams(),
	}
	return nil
}
